[package]
name = "tsunami"
version = "0.1.0"
authors = ["CrimsonVoid"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = { version = "7.0.0", default-features = false, features = ["alloc"] }
ring = { version = "0.16.20", default-features = false, features = [] }
hyper = { version = "0.14.14", default-features = false, features = ["client", "http1", "tcp", "stream"] }
rand = { version = "0.8.4", default-features = false, features = ["small_rng"] }
chrono = { version = "0.4.19", default-features = false, features = ["clock"] }
thiserror = "1.0.30"

[dev-dependencies]
tokio = { version = "1.12.0", default-features = false, features = ["rt", "macros"] }
