[package]
name = "tsunami"
version = "0.1.0"
authors = ["CrimsonVoid"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.30"
nom = { version = "7.1.1", default-features = false, features = ["alloc"] }
ring = { version = "0.16.20", default-features = false }
hyper = { version = "0.14.18", default-features = false, features = ["client", "http1", "tcp"] }
rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }
chrono = { version = "0.4.19", default-features = false, features = ["clock"] }
tokio = { version = "1.17.0", default-features = false, features = ["net", "io-util"] }
futures = { version = "0.3.21", default-features = false, features = ["async-await"] }
bitvec = { version = "1.0.0", default-features = false, features = ["alloc"] }
bitflags = { version = "1.3.2", default-features = false }
byteorder = { version = "1.4.3", default-features = false }
dirs = "4.0.0"

[dev-dependencies]
tokio = { version = "1.17.0", default-features = false, features = ["macros"] }
