[package]
name = "tsunami"
version = "0.1.0"
authors = ["CrimsonVoid"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = { version = "6.2.1", default-features = false, features=["alloc"] }
ring = "0.16.20"
hyper = { version = "0.14.9", default-features = false, features = ["client", "http1", "tcp", "stream"] }
tokio = { version = "1.8.0", features = ["full"] }
futures = "0.3.15"
