[package]
name = "tsunami"
version = "0.1.0"
authors = ["CrimsonVoid"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lalrpop-util = "0.19.5"
logos = "0.12.0"

[build-dependencies]
lalrpop = "0.19.5"
