[package]
name = "tsunami"
version = "0.1.0"
authors = ["CrimsonVoid"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = { version = "7.1.0", default-features = false, features = ["alloc"] }
ring = { version = "0.16.20", default-features = false }
hyper = { version = "0.14.15", default-features = false, features = ["client", "http1", "tcp", "stream"] }
rand = { version = "0.8.4", default-features = false, features = ["small_rng"] }
chrono = { version = "0.4.19", default-features = false, features = ["clock"] }
thiserror = "1.0.30"
async-trait = "0.1.51"
tokio = { version = "1.14.0", default-features = false, features = ["net", "io-util"] }
futures = { version = "0.3.17" }

[dev-dependencies]
tokio = { version = "1.14.0", default-features = false, features = ["net", "rt", "macros", "full"] }
