name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install_rust
      - run: cargo check
      - run: cargo build
      - run: cargo test

  lints:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install_rust
      - run: rustup component add rustfmt clippy
      - run: cargo fmt --all -- --check
        continue-on-error: true
      - run: cargo clippy
